//board.c created Sunday 15/02/2026 at 11:05 updated Sunday 15/02/2026 at 16:58

#include "board.h"
#include "digital_io.h"   /* digital_read(), digital_write(), pin defs  */
#include "bq79616.h"      /* All the bq79616_* functions we'll call     */
#include <stdio.h>        /* snprintf for debug messages                */
#include <string.h>       /* strlen for debug print length              */
#include <math.h>         /* logf for NTC Beta equation temperature     */

/* We use the bq79616 debug print macro.
 * sys_debug is declared extern in bq79616.h and defined in bq79616.c.
 * When sys_debug == true, these messages appear on the UART terminal. */
extern UART_HandleTypeDef huart1;

/* FDCAN1 handle — declared in main.c by CubeMX.
 * Used for control bus heartbeat TX and RX. */
extern FDCAN_HandleTypeDef hfdcan1;
extern FDCAN_HandleTypeDef hfdcan2;

/* USB CDC Virtual COM Port — mirrors all terminal output.
 * CDC_Transmit_FS() is generated by CubeMX USB Device middleware.
 * If USB is not connected, the call returns USBD_BUSY instantly
 * with zero delay — no stall, no performance impact. */
#include "usbd_cdc_if.h"


/* ===============================================================
 *  USART1 DMA + USB CDC transmit helpers
 *
 *  One shared static buffer is the DMA source for ALL terminal
 *  output.  Every transmit goes to BOTH USART1 (via DMA) and
 *  USB CDC (via packet memory copy), so PuTTY on the UART and
 *  a USB terminal see identical output.
 *
 *  USB CDC is ~70x faster than 115200 baud UART, so the mirror
 *  adds negligible overhead.  CDC_Transmit_FS() copies data into
 *  the USB peripheral's packet memory during the call — by the
 *  time it returns, the source buffer is free for UART DMA.
 *
 *  Two usage patterns:
 *
 *  Pattern A — small strings (dbg calls):
 *    uart1_dma_send(data, len);
 *    // copies into static buffer, sends to CDC, fires DMA
 *
 *  Pattern B — large screen buffer (display engine):
 *    char *buf = (char *)uart1_dma_buf();  // get buffer pointer
 *    int pos = snprintf(buf, UART1_TX_SIZE, ...);  // build in-place
 *    uart1_dma_send_buf((uint16_t)pos);    // send to CDC + DMA
 *
 *  Both patterns wait for any in-progress DMA to finish before
 *  touching the buffer, ensuring no data corruption.
 * =============================================================== */
static uint8_t uart1_tx_buf[UART1_TX_SIZE];


/* ---- uart1_dma_wait ----
 * Spin until the UART TX state returns to READY, meaning the
 * previous DMA transfer has fully completed.
 *
 * HAL sets gState = HAL_UART_STATE_BUSY_TX when DMA starts,
 * and the DMA-complete ISR resets it to HAL_UART_STATE_READY.
 *
 * We check for != READY rather than == BUSY_TX because gState
 * can also be HAL_UART_STATE_BUSY_TX_RX if both directions
 * are active simultaneously (unlikely for USART1, but safe). */
void uart1_dma_wait(void)
{
    while (huart1.gState != HAL_UART_STATE_READY)
    {
        /* Spin — typically < 1 ms for small debug strings,
         * up to ~130 ms worst case for a full 1536-byte buffer
         * at 115200 bps.  No HAL_Delay needed because this is
         * genuinely just waiting for hardware to finish. */
    }
}


/* ---- uart1_dma_send ----
 * Copy data into the static DMA buffer, mirror to USB CDC,
 * then fire a UART DMA transfer.
 *
 * USB CDC goes first because CDC_Transmit_FS() copies the data
 * into the USB peripheral's packet memory during the call.
 * Once it returns, our buffer is free for UART DMA to read.
 *
 * If USB is not connected, CDC_Transmit_FS() returns USBD_BUSY
 * instantly — no stall.  We ignore the return value because
 * debug output is best-effort on USB. */
void uart1_dma_send(const uint8_t *data, uint16_t len)
{
    if (len == 0) { return; }

    uart1_dma_wait();     /* Wait for previous transfer */

    /* Clamp to buffer size (safety) */
    if (len > UART1_TX_SIZE)
    {
        len = UART1_TX_SIZE;
    }

    memcpy(uart1_tx_buf, data, len);

    /* Mirror to USB CDC (non-blocking, fail-safe) */
    CDC_Mirror_Write_FS(uart1_tx_buf, len);

    /* Fire UART DMA */
    (void)HAL_UART_Transmit_DMA(&huart1, uart1_tx_buf, len);
}


/* ---- uart1_dma_buf ----
 * Returns a pointer to the internal DMA buffer so callers can
 * build content directly with snprintf, avoiding a memcpy.
 *
 * Waits for any in-progress DMA to finish first — the buffer
 * must not be written while DMA is still reading from it. */
uint8_t *uart1_dma_buf(void)
{
    uart1_dma_wait();
    return uart1_tx_buf;
}


/* ---- uart1_dma_send_buf ----
 * Mirror the internal buffer to USB CDC, then fire a UART DMA
 * transfer.  Call after building content via uart1_dma_buf().
 *
 * Does NOT wait — returns immediately while DMA runs in the
 * background.  The CPU is free to do other work (run the
 * balance state machine, check NFAULT, etc). */
void uart1_dma_send_buf(uint16_t len)
{
    if (len == 0) { return; }

    if (len > UART1_TX_SIZE)
    {
        len = UART1_TX_SIZE;
    }

    /* Mirror to USB CDC (non-blocking, fail-safe) */
    CDC_Mirror_Write_FS(uart1_tx_buf, len);

    /* Fire UART DMA */
    (void)HAL_UART_Transmit_DMA(&huart1, uart1_tx_buf, len);
}


/* ---------------------------------------------------------------
 *  Small helper — prints a string to the debug UART via DMA.
 *  Only sends when sys_debug is true (debug mode).
 *
 *  Uses uart1_dma_send() which copies the string into the
 *  static DMA buffer before firing, so it's safe to call with
 *  stack-local format buffers (like those in dbg_hex/dbg_frame).
 * --------------------------------------------------------------- */
static void board_dbg(const char *msg)
{
    if (sys_debug)
    {
        uart1_dma_send((const uint8_t *)msg,
                       (uint16_t)strlen(msg));
    }
}


/* ===============================================================
 *  Board identity and configuration state
 *
 *  These are set by board_setup_from_config_jumpers() (when
 *  CONFIG_NO_APP is HIGH) or by board_set_defaults() (when
 *  CONFIG_NO_APP is LOW).  The getters below let application.c
 *  and other modules read these values without knowing which
 *  path set them.
 * =============================================================== */
static uint8_t  g_board_address       = 0;     /* 0=master, 1-7=slave */
static uint8_t  g_num_expected_slaves = 0;     /* 0..7                */
static uint8_t  g_active_cell_count   = 16;    /* 6..16               */
static uint16_t g_bal_floor_mv        = 3800;  /* Balance floor (mV)  */

/* The PCB config jumpers pull the MCU input up to 3.3 V when fitted.
 * Open jumpers therefore read back LOW via the MCU's internal pull-down,
 * while fitted jumpers read HIGH and represent a logical '1'. */
static uint8_t board_jumper_bit(dpin_t pin)
{
    return (digital_read(pin) == HIGH) ? 1U : 0U;
}

/* Read the board identity jumpers that define CAN address and the
 * expected slave count on the master.  These are physical topology
 * settings, so we keep using them even when the rest of the board
 * configuration comes from the app/defaults path. */
void board_refresh_identity_from_jumpers(void)
{
    uint8_t addr_j1 = board_jumper_bit(PB9);
    uint8_t addr_j2 = board_jumper_bit(PC12);
    uint8_t addr_j3 = board_jumper_bit(PC2);

    uint8_t slv_j2 = board_jumper_bit(PC3);
    uint8_t slv_j1 = board_jumper_bit(PA0);
    uint8_t slv_j0 = board_jumper_bit(PA1);

    g_board_address = (uint8_t)((addr_j1 << 2) | (addr_j2 << 1) | addr_j3);
    g_num_expected_slaves = (uint8_t)((slv_j2 << 2) | (slv_j1 << 1) | slv_j0);
}


uint8_t board_get_address(void)
{
    return g_board_address;
}

uint8_t board_get_num_expected_slaves(void)
{
    return g_num_expected_slaves;
}

uint8_t board_get_active_cell_count(void)
{
    return g_active_cell_count;
}

uint16_t board_get_bal_floor_mv(void)
{
    return g_bal_floor_mv;
}

void board_load_runtime_config_from_jumpers(void)
{
    uint8_t j1;
    uint8_t j2;
    uint8_t j3;
    uint8_t j4;
    uint8_t jumper_value;
    uint8_t cell_count;
    uint8_t is_lithium_ion;
    uint8_t is_hicap;

    board_refresh_identity_from_jumpers();

    j1 = board_jumper_bit(PB3);
    j2 = board_jumper_bit(PB4);
    j3 = board_jumper_bit(PB5);
    j4 = board_jumper_bit(PB6);
    jumper_value = (uint8_t)((j1 << 3) | (j2 << 2) | (j3 << 1) | j4);
    cell_count = jumper_value + 6U;

    if (cell_count > 16U)
    {
        cell_count = 16U;
    }

    g_active_cell_count = cell_count;
    is_lithium_ion = board_jumper_bit(PB8);
    is_hicap       = board_jumper_bit(PB7);

    if (is_lithium_ion)
    {
        g_bal_floor_mv = is_hicap ? 3400U : 3500U;
    }
    else
    {
        g_bal_floor_mv = 2800U;
    }
}

void board_load_runtime_defaults(void)
{
    board_refresh_identity_from_jumpers();
    g_active_cell_count = 16U;
    g_bal_floor_mv      = 3800U;
}


/* ===============================================================
 *  board_setup_from_config_jumpers
 *
 *  Reads ALL hardware config jumpers on the PCB and configures
 *  the BQ79616 and MCU warning thresholds accordingly.
 *
 *  Called when CONFIG_NO_APP (PC10) is fitted at startup — this
 *  means the board is being deployed standalone without a PC
 *  or app to configure it.
 *
 *  JUMPER PIN MAP  (from CPM-4-16.ioc):
 *
 *    Board address (3 bits):
 *      CONFIG_ADDRESS_J1 = PB9   (MSB, bit 2)
 *      CONFIG_ADDRESS_J2 = PC12  (bit 1)
 *      CONFIG_ADDRESS_J3 = PC2   (LSB, bit 0)
 *      000=master, 001=slave1 ... 111=slave7
 *
 *    Expected slave count (3 bits):
 *      NUM_SLAVES_J2 = PC3  (MSB, bit 2)
 *      NUM_SLAVES_J1 = PA0  (bit 1)
 *      NUM_SLAVES_J0 = PA1  (LSB, bit 0)
 *      Binary 0..7
 *
 *    Cell count (4 bits):
 *      CONFIG_CELLS_J1 = PB3  (MSB, bit 3)
 *      CONFIG_CELLS_J2 = PB4  (bit 2)
 *      CONFIG_CELLS_J3 = PB5  (bit 1)
 *      CONFIG_CELLS_J4 = PB6  (LSB, bit 0)
 *      Binary value + 6 = number of cells (6..16)
 *
 *    Chemistry and mode:
 *      CONFIG_ION_LFP       = PB8  (1=Li-Ion, 0=LiFePO4)
 *      CONFIG_HICAP_LONGLIFE = PB7 (1=Hi-Cap, 0=Long-Life)
 *
 *  All config pins use internal pull-downs in MX_GPIO_Init().
 *  Open jumper   -> GPIO LOW  -> logical 0
 *  Fitted jumper -> GPIO HIGH -> logical 1
 * =============================================================== */
bool board_setup_from_config_jumpers(uint8_t dev_id)
{
    board_refresh_identity_from_jumpers();

    /* ------ Step 1: Read board address jumpers ------
     *
     * Three bits: J1(MSB) J2 J3(LSB) -> 0..7
     *   0 = master board
     *   1..7 = slave boards on the daisy chain
     */
    uint8_t addr_j1 = (g_board_address >> 2) & 0x1U;
    uint8_t addr_j2 = (g_board_address >> 1) & 0x1U;
    uint8_t addr_j3 = g_board_address & 0x1U;

    /* ------ Step 2: Read expected slave count jumpers ------
     *
     * Three bits: J2(MSB) J1 J0(LSB) -> 0..7
     * Only meaningful on the master board, but we read it
     * regardless so the display can show the setting.
     */
    /* ------ Step 3: Read the four cell-count jumpers ------
     *
     * The jumpers form a 4-bit binary number:
     *   J1 = bit 3 (MSB), J2 = bit 2, J3 = bit 1, J4 = bit 0 (LSB)
     *
     * That binary value (0..10) is added to 6 to give the cell count.
     * For example:  J1=1 J2=0 J3=1 J4=0  ->  binary 1010 = 10  ->  10+6 = 16 cells.
     *
     * Values above 10 (i.e. 11..15) are invalid because the BQ79616
     * only supports up to 16 cells, and 6+10 = 16.
     */
    uint8_t j1 = board_jumper_bit(PB3);  /* CONFIG_CELLS_J1 */
    uint8_t j2 = board_jumper_bit(PB4);  /* CONFIG_CELLS_J2 */
    uint8_t j3 = board_jumper_bit(PB5);  /* CONFIG_CELLS_J3 */
    uint8_t j4 = board_jumper_bit(PB6);  /* CONFIG_CELLS_J4 */

    /* Combine the four bits into one number (0..15) */
    uint8_t jumper_value = (uint8_t)((j1 << 3) | (j2 << 2) | (j3 << 1) | j4);

    /* Cell count = jumper value + 6.  Valid jumper range is 0..10 -> 6..16 cells */
    uint8_t cell_count = jumper_value + 6;

    /* ------ Step 4: Read the chemistry jumper ------
     *
     * CONFIG_ION_LFP on PB8:
     *   HIGH (1) = Lithium-Ion  (NMC / NCA - higher voltage per cell)
     *   LOW  (0) = LiFePO4     (LFP - lower voltage per cell)
     */
    uint8_t is_lithium_ion = board_jumper_bit(PB8);

    /* ------ Step 5: Read the capacity / longevity jumper ------
     *
     * CONFIG_HICAP_LONGLIFE on PB7:
     *   HIGH (1) = High-Capacity mode   (charge fuller, discharge deeper)
     *   LOW  (0) = Long-Life mode       (gentler limits extend cycle life)
     */
    uint8_t is_hicap = board_jumper_bit(PB7);

    /* ------ Print what we read (debug) ------ */
    {
        char buf[160];

        snprintf(buf, sizeof(buf),
                 "\r\n=== BOARD CONFIG JUMPERS ===\r\n"
                 "  Raw addr   : J1=%u J2=%u J3=%u\r\n"
                 "  Address   : %u (%s)\r\n"
                 "  Exp slaves: %u\r\n",
                 addr_j1, addr_j2, addr_j3,
                 g_board_address,
                 (g_board_address == 0) ? "MASTER" : "SLAVE",
                 g_num_expected_slaves);
        board_dbg(buf);

        snprintf(buf, sizeof(buf),
                 "  Cells J1=%u J2=%u J3=%u J4=%u  -> %u cells\r\n"
                 "  Chemistry : %s\r\n"
                 "  Mode      : %s\r\n",
                 j1, j2, j3, j4, cell_count,
                 is_lithium_ion ? "Lithium-Ion" : "LiFePO4",
                 is_hicap       ? "High-Capacity" : "Long-Life");
        board_dbg(buf);
    }

    /* ------ Step 6: Validate the cell count ------
     *
     * The BQ79616 supports 6 to 16 cells.  If the jumper value
     * is above 10 the cell count exceeds 16 which is impossible.
     * Rather than sending a bad value to the chip, we stop here.
     */
    if (cell_count > 16)
    {
        char buf[80];

        snprintf(buf, sizeof(buf),
                 "  ERROR: jumper value %u -> %u cells (max 16)!\r\n",
                 jumper_value, cell_count);
        board_dbg(buf);
        board_dbg("=== BOARD CONFIG FAILED ===\r\n");
        return false;
    }

    g_active_cell_count = cell_count;

    /* ------ Step 7: Tell the BQ79616 how many cells are connected ------
     *
     * This writes the ACTIVE_CELL register so the ADC knows which
     * cell channels to scan.  Same as doing:
     *   bq79616_set_active_cells(0x01, 16);
     * ...but now the number comes from the jumpers instead of being hardcoded.
     */
    if (!bq79616_set_active_cells(dev_id, cell_count))
    {
        board_dbg("  ERROR: bq79616_set_active_cells failed!\r\n");
        board_dbg("=== BOARD CONFIG FAILED ===\r\n");
        return false;
    }

    /* ------ Step 8: Look up the OV and UV thresholds ------
     *
     * The correct thresholds depend on BOTH the chemistry type
     * and the capacity/longevity mode.  This gives four combos:
     *
     *   Chemistry    Mode         OV (mV)   UV (mV)   Bal Floor (mV)
     *   ------------ ------------ --------- --------- ---------------
     *   Lithium-Ion  High-Cap     4225      2850      3400
     *   Lithium-Ion  Long-Life    4175      3050*     3500
     *   LiFePO4      High-Cap     3650      2500      2800
     *   LiFePO4      Long-Life    3500      2950      2800
     *
     *  * NOTE: The original spec says Li-Ion Long-Life UV = 3450 mV,
     *    but the BQ79616 UV comparator maxes out at 3100 mV (see
     *    bq79616_set_uv_thresh).  We clamp to 3050 mV here which
     *    is the closest valid 50 mV step.  If you need 3450 mV
     *    protection you will need to do it in software by reading
     *    cell voltages periodically and checking yourself.
     *
     *  MCU warning thresholds are derived from the BQ thresholds:
     *    OV  warning = OV  - 25 mV  (early warning before BQ trips)
     *    BAL warning = OV  - 90 mV  (start balancing before OV)
     *    UV  warning = UV  + 50 mV  (early warning before BQ trips)
     */
    uint16_t ov_mv;         /* Overvoltage threshold in millivolts  */
    uint16_t uv_mv;         /* Undervoltage threshold in millivolts */

    if (is_lithium_ion)
    {
        if (is_hicap)
        {
            /* Li-Ion, High-Capacity: charge high, discharge deep */
            ov_mv        = 4225;
            uv_mv        = 2850;
            g_bal_floor_mv = 3400;
        }
        else
        {
            /* Li-Ion, Long-Life: gentler limits for more cycles  */
            ov_mv        = 4175;
            uv_mv        = 3050;   /* Clamped from 3450 - see note above */
            g_bal_floor_mv = 3500;
        }
    }
    else
    {
        if (is_hicap)
        {
            /* LiFePO4, High-Capacity */
            ov_mv        = 3650;
            uv_mv        = 2500;
            g_bal_floor_mv = 2800;
        }
        else
        {
            /* LiFePO4, Long-Life */
            ov_mv        = 3500;
            uv_mv        = 2950;
            g_bal_floor_mv = 2800;
        }
    }

    /* Print the thresholds we are about to apply */
    {
        char buf[128];

        snprintf(buf, sizeof(buf),
                 "  OV = %u mV, UV = %u mV, Bal floor = %u mV\r\n"
                 "  OV warn = %u, BAL warn = %u, UV warn = %u\r\n",
                 ov_mv, uv_mv, g_bal_floor_mv,
                 ov_mv - 25, ov_mv - 90, uv_mv + 50);
        board_dbg(buf);
    }

    /* ------ Step 9: Set the overvoltage threshold ------ */
    if (!bq79616_set_ov_thresh(dev_id, ov_mv))
    {
        board_dbg("  ERROR: bq79616_set_ov_thresh failed!\r\n");
        board_dbg("=== BOARD CONFIG FAILED ===\r\n");
        return false;
    }

    /* ------ Step 10: Set the undervoltage threshold ------ */
    if (!bq79616_set_uv_thresh(dev_id, uv_mv))
    {
        board_dbg("  ERROR: bq79616_set_uv_thresh failed!\r\n");
        board_dbg("=== BOARD CONFIG FAILED ===\r\n");
        return false;
    }

    /* ------ Step 11: Set MCU warning thresholds ------
     *
     * These are software thresholds checked every 500 ms in the
     * display refresh using live cell voltage reads.  They drive
     * MCU GPIO warning indicators:
     *   PA5 HIGH if any cell >= (OV - 25 mV)  overvoltage warning
     *   PA4 HIGH if any cell >= (OV - 90 mV)  balance warning
     *   PA6 HIGH if any cell <= (UV + 50 mV)  undervoltage warning
     */
    board_set_ov_warn_thresh(ov_mv - 25);
    board_set_bal_warn_thresh(ov_mv - 90);
    board_set_uv_warn_thresh(uv_mv + 50);

    /* ------ Done! ------ */
    board_dbg("=== BOARD CONFIG OK ===\r\n");
    return true;
}


/* ===============================================================
 *  board_set_defaults
 *
 *  Hardcoded safe configuration for when CONFIG_NO_APP is LOW
 *  (a PC or app will manage the board later via CAN/USB).
 *
 *  Sets Li-Ion Long-Life defaults:
 *    16 cells, OV=4175, UV=3100
 *    MCU warnings: OV=4150, BAL=4085, UV=3150
 *    Balance floor = 3800 mV
 *
 *  Board identity for CAN is still taken from the physical
 *  address/slave-count jumpers so multi-board setups work even
 *  in the app-managed/defaults path.
 * =============================================================== */
bool board_set_defaults(uint8_t dev_id)
{
    char identity_buf[96];
    uint8_t addr_j1;
    uint8_t addr_j2;
    uint8_t addr_j3;

    board_dbg("\r\n=== BOARD DEFAULTS (NO_APP=LOW) ===\r\n");

    board_refresh_identity_from_jumpers();
    g_active_cell_count   = 16;
    g_bal_floor_mv        = 3800;
    addr_j1 = (g_board_address >> 2) & 0x1U;
    addr_j2 = (g_board_address >> 1) & 0x1U;
    addr_j3 = g_board_address & 0x1U;

    snprintf(identity_buf, sizeof(identity_buf),
             "  Identity from jumpers: raw J1=%u J2=%u J3=%u, addr=%u (%s), slaves=%u\r\n",
             addr_j1, addr_j2, addr_j3,
             g_board_address,
             (g_board_address == BOARD_ADDR_MASTER) ? "MASTER" : "SLAVE",
             g_num_expected_slaves);
    board_dbg(identity_buf);

    if (!bq79616_set_active_cells(dev_id, 16))
    {
        board_dbg("  ERROR: set_active_cells failed!\r\n");
        return false;
    }

    if (!bq79616_set_ov_thresh(dev_id, 4175))
    {
        board_dbg("  ERROR: set_ov_thresh failed!\r\n");
        return false;
    }

    if (!bq79616_set_uv_thresh(dev_id, 3100))
    {
        board_dbg("  ERROR: set_uv_thresh failed!\r\n");
        return false;
    }

    board_set_ov_warn_thresh(4150);
    board_set_bal_warn_thresh(4085);
    board_set_uv_warn_thresh(3150);

    board_dbg("  16S, OV=4175, UV=3100\r\n");
    board_dbg("=== BOARD DEFAULTS OK ===\r\n");
    return true;
}


/* ===============================================================
 *  CONTACTOR CONTROL
 *
 *  Three TPS1H200A-Q1 smart high-side switches drive the battery
 *  contactors.  Each one is basically a fancy MOSFET with built-in
 *  protection and diagnostics:
 *
 *    IN pin       = MCU tells it to turn ON (HIGH) or OFF (LOW)
 *    FAULT pin    = open-drain output, pulled HIGH externally.
 *                   Goes LOW when there's a problem (overload,
 *                   short-to-ground, open load, or thermal issue).
 *    DIAG_EN pin  = enables/disables the diagnostic features.
 *                   All 3 drivers share one DIAG_EN line (PA15).
 *
 *  PIN MAP (from CPM-4-16.ioc):
 *
 *    Function            Pin    Direction   Notes
 *    ------------------  -----  ---------   ----------------------------
 *    DIAG_EN_CONTACTORS  PA15   output      Shared diag enable for all 3
 *    MCU_CONTACTOR-      PC9    output      Negative contactor IN
 *    MCU_CONTACTOR+      PD5    output      Positive contactor IN
 *    MCU_PRECHARGE       PD3    output      Precharge contactor IN
 *    MCU_CONTACTOR-FAULT PD2    input       Negative FAULT (active LOW)
 *    MCU_CONTACTOR+FAULT PC8    input       Positive FAULT (active LOW)
 *    MCU_PRECHARGE_FAULT PD4    input       Precharge FAULT (active LOW)
 *    MCU_HV_PRESENT      PB14   input       HIGH = HV bus is charged
 *
 * =============================================================== */


/* ---------------------------------------------------------------
 *  contactor_check_fault  -  Read a TPS1H200A FAULT pin
 *
 *  The FAULT pin is open-drain with an external pull-up resistor.
 *  Normal operation:  FAULT = HIGH  (pulled up, no fault)
 *  Fault condition:   FAULT = LOW   (driver pulls it down)
 *
 *  Possible faults (from TPS1H200A datasheet table 7-2):
 *    - Overload or short-to-GND  (current limit triggered)
 *    - Open load or short-to-battery  (output current too low)
 *    - Thermal shutdown  (chip too hot, output turned off)
 *    - Thermal swing  (rapid temperature change detected)
 *
 *  Since the FAULT pin is just one digital signal, we can't tell
 *  WHICH fault happened - only that SOMETHING is wrong.  The
 *  TPS1H200A's CL (current limit) pin analog voltage could be
 *  read via ADC to distinguish fault types, but we don't do that
 *  here.
 *
 *  Parameters:
 *    fault_pin  -  the dpin_t for the FAULT input (e.g. PD2)
 *    name       -  human-readable name for debug prints
 *
 *  Returns:
 *    true   -  no fault (FAULT pin is HIGH = normal)
 *    false  -  fault detected (FAULT pin is LOW)
 * --------------------------------------------------------------- */
static bool contactor_check_fault(dpin_t fault_pin, const char *name)
{
    /* Read the FAULT pin.  LOW = fault, HIGH = OK. */
    if (digital_read(fault_pin) == LOW)
    {
        /* Something is wrong with this driver.
         * Print which one so the user knows where to look. */
        char buf[80];

        snprintf(buf, sizeof(buf),
                 "  FAULT: %s driver reports fault (pin LOW)!\r\n",
                 name);
        board_dbg(buf);

        board_dbg("  Possible causes (TPS1H200A-Q1):\r\n");
        board_dbg("    - Overload or short-to-GND\r\n");
        board_dbg("    - Open load (contactor coil disconnected?)\r\n");
        board_dbg("    - Thermal shutdown or thermal swing\r\n");
        return false;   /* Fault detected */
    }

    return true;   /* No fault - all good */
}


/* ---------------------------------------------------------------
 *  contactor_all_off  -  Emergency: open every contactor
 *
 *  Called when something goes wrong during startup.  Opens all
 *  three contactors (precharge, positive, negative) and disables
 *  diagnostics.  This puts the system in a safe state.
 *
 *  We open in reverse order: precharge first (stop charging the
 *  bus), then positive (disconnect load side), then negative
 *  (disconnect battery side).
 * --------------------------------------------------------------- */
static void contactor_all_off(void)
{
    board_dbg("  -> Opening all contactors (safe state)\r\n");

    digital_write(PD3, LOW);    /* Open precharge  (MCU_PRECHARGE)  */
    digital_write(PD5, LOW);    /* Open positive   (MCU_CONTACTOR+) */
    digital_write(PC9, LOW);    /* Open negative   (MCU_CONTACTOR-) */

    /* Disable diagnostics to save power.
     * With DIAG_EN LOW and IN LOW, the TPS1H200A enters its
     * lowest power state (< 500 nA standby current). */
    digital_write(PA15, LOW);   /* DIAG_EN_CONTACTORS off */
}


/* ===============================================================
 *  board_contactor_startup
 *
 *  Closes the battery contactors in the correct order, checking
 *  for TPS1H200A driver faults at each step.
 *
 *  The sequence follows the Nissan Leaf charge turn-on timing:
 *
 *    Time (ms)   Action
 *    ---------   ----------------------------------
 *         0      Close negative contactor
 *       200      Close precharge contactor
 *    200-700     Wait for HV bus to charge (PB14 HIGH)
 *       ~700     Close positive contactor
 *       ~800     Open precharge contactor
 *
 *  If PB14 does not go HIGH within 500 ms of precharge closing,
 *  something is wrong (precharge resistor blown, contactor stuck
 *  open, etc.) so we abort and open everything.
 * =============================================================== */
bool board_contactor_startup(void)
{
    board_dbg("\r\n=== CONTACTOR STARTUP BEGIN ===\r\n");

    /* ------ Step 1: Enable diagnostics on all 3 drivers ------
     *
     * PA15 is wired to the DIAG_EN pin on all three TPS1H200A
     * drivers.  Setting it HIGH enables fault reporting on the
     * FAULT pins.  Without this, the FAULT pins don't indicate
     * problems (though the internal protections still work).
     */
    board_dbg("  Enabling driver diagnostics (PA15 HIGH)\r\n");
    digital_write(PA15, HIGH);

    /* Give the drivers a moment to wake up their diagnostic
     * circuitry.  The TPS1H200A needs very little time here
     * but 5 ms is safe. */
    HAL_Delay(5);

    /* ------ Step 2: Close negative contactor ------
     *
     * PC9 = MCU_CONTACTOR- = IN pin on the negative TPS1H200A.
     * Setting it HIGH turns on the MOSFET inside the driver,
     * which sends current through the contactor coil, pulling
     * the contacts closed.
     *
     * The negative contactor closes FIRST because it connects
     * the battery ground side.  No current flows yet because
     * the positive side is still open.
     */
    board_dbg("  Closing NEGATIVE contactor (PC9 HIGH)\r\n");
    digital_write(PC9, HIGH);

    /* Wait 10 ms for the driver to settle and the contactor
     * to physically close, then check for faults.
     * The TPS1H200A's open-load deglitch time is ~300 us,
     * so 10 ms is more than enough. */
    HAL_Delay(10);

    if (!contactor_check_fault(PD2, "CONTACTOR-"))
    {
        /* Negative driver faulted - abort everything */
        board_dbg("=== CONTACTOR STARTUP ABORTED (NEG FAULT) ===\r\n");
        contactor_all_off();
        return false;
    }

    /* ------ Step 3: Wait 200 ms ------
     *
     * This gap between closing the negative and starting
     * precharge matches the Nissan Leaf timing.  It ensures
     * the negative contactor is fully seated before we start
     * pushing current through the precharge path.
     * (We already waited 10 ms above, so 190 ms more.)
     */
    HAL_Delay(190);

    /* ------ Step 4: Close precharge contactor ------
     *
     * PD3 = MCU_PRECHARGE = IN pin on the precharge TPS1H200A.
     * The precharge contactor has a resistor in series that
     * limits inrush current while the DC bus capacitors charge
     * up.  Without precharge, slamming the positive contactor
     * closed would cause a huge current spike that could weld
     * the contactor contacts or blow fuses.
     */
    board_dbg("  Closing PRECHARGE contactor (PD3 HIGH)\r\n");
    digital_write(PD3, HIGH);

    /* Wait 10 ms for the driver to settle, then check fault */
    HAL_Delay(10);

    if (!contactor_check_fault(PD4, "PRECHARGE"))
    {
        /* Precharge driver faulted - abort */
        board_dbg("=== CONTACTOR STARTUP ABORTED (PCHG FAULT) ===\r\n");
        contactor_all_off();
        return false;
    }

    /* ------ Step 5: Wait for HV bus to charge (PB14 HIGH) ------
     *
     * PB14 = MCU_HV_PRESENT.  This pin is connected to a voltage
     * divider on the DC bus.  When the bus capacitors charge up
     * through the precharge resistor, PB14 goes HIGH.
     *
     * We poll every 10 ms and give it a maximum of 500 ms.
     * If PB14 doesn't go HIGH in time, something is wrong:
     *   - Precharge resistor is blown / open
     *   - Contactor didn't actually close
     *   - DC bus has a short circuit
     *   - Voltage divider circuit fault
     */
    board_dbg("  Waiting for HV bus to charge (PB14 HIGH)...\r\n");

    {
        /* 500 ms timeout, polling every 10 ms = 50 iterations max */
        uint16_t polls = 0;
        const uint16_t max_polls = 50;   /* 50 x 10 ms = 500 ms */
        bool hv_ok = false;

        while (polls < max_polls)
        {
            /* Check if the bus voltage has reached the threshold */
            if (digital_read(PB14) == HIGH)
            {
                hv_ok = true;
                break;
            }

            /* Also check precharge fault each iteration -
             * if the precharge driver faults mid-charge we
             * want to know immediately, not wait 500 ms. */
            if (!contactor_check_fault(PD4, "PRECHARGE"))
            {
                board_dbg("=== CONTACTOR STARTUP ABORTED "
                          "(PCHG FAULT DURING CHARGE) ===\r\n");
                contactor_all_off();
                return false;
            }

            HAL_Delay(10);
            polls++;
        }

        if (!hv_ok)
        {
            /* Timed out - HV bus never charged up */
            char buf[64];

            snprintf(buf, sizeof(buf),
                     "  TIMEOUT: PB14 not HIGH after %u ms!\r\n",
                     (unsigned)(polls * 10));
            board_dbg(buf);
            board_dbg("  Check: precharge resistor, contactor, bus\r\n");
            board_dbg("=== CONTACTOR STARTUP ABORTED (TIMEOUT) ===\r\n");
            contactor_all_off();
            return false;
        }

        /* Print how long it took - useful for diagnostics */
        {
            char buf[64];

            snprintf(buf, sizeof(buf),
                     "  HV bus charged OK after ~%u ms\r\n",
                     (unsigned)(polls * 10));
            board_dbg(buf);
        }
    }

    /* ------ Step 6: Close positive contactor ------
     *
     * PD5 = MCU_CONTACTOR+ = IN pin on the positive TPS1H200A.
     * Now that the bus is pre-charged, it's safe to close the
     * main positive contactor.  The voltage across the contactor
     * contacts is nearly zero (bus is already at battery voltage)
     * so there's no inrush current spike.
     */
    board_dbg("  Closing POSITIVE contactor (PD5 HIGH)\r\n");
    digital_write(PD5, HIGH);

    /* Wait 10 ms then check for faults */
    HAL_Delay(10);

    if (!contactor_check_fault(PC8, "CONTACTOR+"))
    {
        /* Positive driver faulted - abort */
        board_dbg("=== CONTACTOR STARTUP ABORTED (POS FAULT) ===\r\n");
        contactor_all_off();
        return false;
    }

    /* ------ Step 7: Open precharge contactor ------
     *
     * The precharge path is no longer needed because the main
     * positive contactor is now carrying the current.  Leaving
     * precharge closed wastes energy through the resistor and
     * could overheat it.
     *
     * Wait 100 ms after positive closes to ensure the main
     * contactor is fully seated before removing the parallel
     * precharge path.
     */
    HAL_Delay(100);

    board_dbg("  Opening PRECHARGE contactor (PD3 LOW)\r\n");
    digital_write(PD3, LOW);

    /* ------ Final fault check ------
     *
     * Do one last check on both main contactors now that
     * the full load current is flowing through them.
     */
    HAL_Delay(10);

    if (!contactor_check_fault(PD2, "CONTACTOR-"))
    {
        board_dbg("=== CONTACTOR STARTUP ABORTED "
                  "(NEG FAULT UNDER LOAD) ===\r\n");
        contactor_all_off();
        return false;
    }

    if (!contactor_check_fault(PC8, "CONTACTOR+"))
    {
        board_dbg("=== CONTACTOR STARTUP ABORTED "
                  "(POS FAULT UNDER LOAD) ===\r\n");
        contactor_all_off();
        return false;
    }

    board_dbg("=== CONTACTOR STARTUP OK - HV BUS LIVE ===\r\n");
    return true;
}


/* ===============================================================
 *  board_contactor_shutdown
 *
 *  Opens the battery contactors in the safe reverse order:
 *    1. Positive first  (disconnect load from battery)
 *    2. Precharge       (in case it's still on for some reason)
 *    3. Negative last   (disconnect battery ground)
 *
 *  The gaps between steps give each contactor time to physically
 *  open and extinguish any arc across the contacts.  The positive
 *  opens first because it's carrying the main current - once it's
 *  open, the negative has no current to interrupt.
 *
 *  We also disable driver diagnostics afterwards to save power.
 *  With DIAG_EN and IN both LOW, each TPS1H200A enters standby
 *  at < 500 nA.
 * =============================================================== */
void board_contactor_shutdown(void)
{
    board_dbg("\r\n=== CONTACTOR SHUTDOWN BEGIN ===\r\n");

    /* ------ Step 1: Open positive contactor ------
     *
     * PD5 LOW = turn off the positive TPS1H200A MOSFET.
     * The contactor coil de-energises and the spring opens
     * the contacts.  The TPS1H200A has an internal clamp
     * diode that handles the inductive kick from the coil.
     */
    board_dbg("  Opening POSITIVE contactor (PD5 LOW)\r\n");
    digital_write(PD5, LOW);

    /* Wait 50 ms for the contactor to physically open */
    HAL_Delay(50);

    /* ------ Step 2: Open precharge contactor ------
     *
     * PD3 LOW.  This should already be open from the startup
     * sequence step 7, but we do it here as a safety measure.
     * Belt and braces!
     */
    board_dbg("  Opening PRECHARGE contactor (PD3 LOW)\r\n");
    digital_write(PD3, LOW);

    /* Wait 50 ms */
    HAL_Delay(50);

    /* ------ Step 3: Open negative contactor ------
     *
     * PC9 LOW.  No current flowing through it at this point
     * because the positive is already open.  This is the safest
     * order - opening the negative under load could cause arcing.
     */
    board_dbg("  Opening NEGATIVE contactor (PC9 LOW)\r\n");
    digital_write(PC9, LOW);

    /* ------ Step 4: Disable diagnostics ------
     *
     * PA15 LOW.  Puts all three TPS1H200A drivers into their
     * lowest power state.  The FAULT pins become inactive but
     * that doesn't matter because everything is off now.
     */
    HAL_Delay(10);
    board_dbg("  Disabling driver diagnostics (PA15 LOW)\r\n");
    digital_write(PA15, LOW);

    board_dbg("=== CONTACTOR SHUTDOWN COMPLETE ===\r\n");
}


/* ===============================================================
 *  MCU-level voltage warning outputs
 *
 *  Three GPIOs act as live status indicators:
 *    PA5 = MCU_OVER_VOLTAGE   (HIGH when any cell is too high)
 *    PA4 = MCU_BALANCING      (HIGH when any cell needs balancing)
 *    PA6 = MCU_UNDER_VOLTAGE  (HIGH when any cell is too low)
 *
 *  Thresholds stored in static variables, set once at startup.
 *  board_check_voltage_warnings() compares every cell against
 *  these thresholds each loop pass.
 *
 *  Non-latching: pin goes LOW the instant no cell meets the
 *  condition.  No hysteresis by design — these are informational
 *  warnings, not fault latches.
 * =============================================================== */

/* ---- Static storage for the three thresholds ----
 *
 * Initialised to 0 which means "not configured".
 * board_check_voltage_warnings() skips any threshold that
 * is 0, so warnings are inactive until setters are called.
 */
static uint16_t warn_ov_mv  = 0;   /* OV:  trigger when cell >= this */
static uint16_t warn_bal_mv = 0;   /* BAL: trigger when cell >= this */
static uint16_t warn_uv_mv  = 0;   /* UV:  trigger when cell <= this */


/* ---------------------------------------------------------------
 *  board_set_ov_warn_thresh  –  Set overvoltage warning level
 *
 *  When any cell voltage >= this value, PA5 goes HIGH.
 *  Typical: 4150 mV (25 mV below BQ79616 OV fault at 4175).
 * --------------------------------------------------------------- */
void board_set_ov_warn_thresh(uint16_t mv)
{
    warn_ov_mv = mv;

    char buf[64];

    snprintf(buf, sizeof(buf),
             "  OV  warn thresh = %u mV (PA5)\r\n",
             (unsigned)mv);
    board_dbg(buf);
}


/* ---------------------------------------------------------------
 *  board_set_bal_warn_thresh  –  Set balance warning level
 *
 *  When any cell voltage >= this value, PA4 goes HIGH.
 *  Typical: 4085 mV (signals cells are nearing full charge
 *  and balancing should be active).
 * --------------------------------------------------------------- */
void board_set_bal_warn_thresh(uint16_t mv)
{
    warn_bal_mv = mv;

    char buf[64];

    snprintf(buf, sizeof(buf),
             "  BAL warn thresh = %u mV (PA4)\r\n",
             (unsigned)mv);
    board_dbg(buf);
}


/* ---------------------------------------------------------------
 *  board_set_uv_warn_thresh  –  Set undervoltage warning level
 *
 *  When any cell voltage <= this value, PA6 goes HIGH.
 *  Typical: 3150 mV (50 mV above BQ79616 UV fault at 3100).
 * --------------------------------------------------------------- */
void board_set_uv_warn_thresh(uint16_t mv)
{
    warn_uv_mv = mv;

    char buf[64];

    snprintf(buf, sizeof(buf),
             "  UV  warn thresh = %u mV (PA6)\r\n",
             (unsigned)mv);
    board_dbg(buf);
}


/* ---------------------------------------------------------------
 *  board_check_voltage_warnings  –  Scan cells, drive GPIOs
 *
 *  Walks through the cell voltage array and checks each cell
 *  against the three thresholds.  If ANY cell triggers a
 *  condition, the GPIO goes HIGH.  If NO cell triggers, LOW.
 *
 *  Cost: ~16 comparisons + 3 GPIO writes.  No UART, no BQ79616
 *  register access — just reading numbers already in RAM.
 *
 *  Parameters:
 *    cell_mv   - array of cell voltages in millivolts
 *    num_cells - how many valid entries (1..16)
 * --------------------------------------------------------------- */
void board_check_voltage_warnings(const int32_t cell_mv[],
                                  uint8_t       num_cells)
{
    uint8_t ov_triggered  = 0;   /* 1 if any cell >= OV threshold  */
    uint8_t bal_triggered = 0;   /* 1 if any cell >= BAL threshold */
    uint8_t uv_triggered  = 0;   /* 1 if any cell <= UV threshold  */
    uint8_t i;

    /* Single pass through all cells, checking all three
     * conditions at once for efficiency. */
    for (i = 0; i < num_cells; i++)
    {
        int32_t v = cell_mv[i];

        /* Skip invalid readings (BQ reset value = 0 mV,
         * or negative from conversion errors).
         * A valid lithium cell is always above 1000 mV. */
        if (v < 1000)
        {
            continue;
        }

        /* Overvoltage: cell >= threshold */
        if ((warn_ov_mv > 0) && (v >= (int32_t)warn_ov_mv))
        {
            ov_triggered = 1;
        }

        /* Balance: cell >= threshold */
        if ((warn_bal_mv > 0) && (v >= (int32_t)warn_bal_mv))
        {
            bal_triggered = 1;
        }

        /* Undervoltage: cell <= threshold (note <= direction) */
        if ((warn_uv_mv > 0) && (v <= (int32_t)warn_uv_mv))
        {
            uv_triggered = 1;
        }
    }

    /* Drive the three GPIO outputs.
     * Non-latching: pin goes LOW immediately when
     * the condition clears. */
    digital_write(PA5, ov_triggered  ? HIGH : LOW);  /* MCU_OVER_VOLTAGE  */
    digital_write(PA4, bal_triggered ? HIGH : LOW);   /* MCU_BALANCING     */
    digital_write(PA6, uv_triggered  ? HIGH : LOW);   /* MCU_UNDER_VOLTAGE */
}


/* ---------------------------------------------------------------
 *  Static result-line buffers
 *
 *  Each measurement function stores its last formatted result
 *  here.  The display engine in application.c reads these via
 *  getter functions, so it can print a clean status screen
 *  without the measurement functions needing to know about the
 *  display layout.
 * --------------------------------------------------------------- */
static char iso_line_buf[96]       = "ISO: ---";
static char bal_temp_line_buf[48]  = "BAL TEMP: ---";
static char batt_temp_line_buf[96] = "BATT TEMP: ---";


const char *board_get_iso_line(void)
{
    return iso_line_buf;
}

const char *board_get_bal_temp_line(void)
{
    return bal_temp_line_buf;
}

const char *board_get_batt_temp_line(void)
{
    return batt_temp_line_buf;
}


/* ===============================================================
 *  Insulation resistance measurement
 *
 *  Measures the isolation between the HV battery system and the
 *  vehicle chassis (body/frame) ground.
 *
 *  WHY THIS MATTERS:
 *    In an EV, the battery is "floating" — neither terminal is
 *    connected to chassis.  If insulation breaks down (e.g. a
 *    wire chafes through its jacket and touches the chassis),
 *    touching the other terminal could be lethal.  This circuit
 *    continuously monitors that the insulation is intact.
 *
 *  HOW THE CIRCUIT WORKS:
 *
 *    R268 and R269 (both 180 MΩ) form a balanced voltage divider
 *    from CELL_TOP to GNDHV, with the midpoint connected to
 *    chassis GND.  This deliberately creates a tiny, safe leakage
 *    current (~167 nA at 60V) that biases chassis to exactly
 *    half the pack voltage.
 *
 *    R270 (400 MΩ) and R272 (2.74 MΩ) then divide that chassis
 *    voltage down to a level the BQ79616 GPIO6 ADC can measure
 *    (0-5V range).
 *
 *    R271 (10 kΩ) and C270 (3.3 nF) are just an RC anti-alias
 *    filter to clean up noise before the ADC.
 *
 *  WHAT WE MEASURE:
 *    If insulation is perfect (infinite resistance between HV
 *    and chassis), the ADC reads exactly the value corresponding
 *    to V_pack/2 through the divider.
 *
 *    If insulation degrades, the chassis voltage shifts away
 *    from V_pack/2.  The direction tells us which side the
 *    fault is on, and the magnitude tells us the resistance.
 *
 *  THRESHOLDS (per UN ECE R100 / industry practice):
 *
 *    UN R100 requires minimum 500 Ω/V for AC systems and
 *    100 Ω/V for DC systems.  These scale with pack voltage:
 *      60V pack:  warn = 30 kΩ,   fault = 6 kΩ
 *      400V pack: warn = 200 kΩ,  fault = 40 kΩ
 *
 *    For practical monitoring (catching degradation early),
 *    we also flag anything below 1 MΩ as abnormal.  Most
 *    healthy EV insulation measures 10+ MΩ.
 *
 *    Status levels (from healthy to dangerous):
 *      OK       — Rf > 1 MΩ     (healthy insulation)
 *      LOW      — Rf > 500 Ω/V  (degrading, schedule service)
 *      WARNING  — Rf > 100 Ω/V  (UN R100 AC limit breached)
 *      FAULT    — Rf ≤ 100 Ω/V  (UN R100 DC limit breached)
 * =============================================================== */

/* Resistor values in kilo-ohms (avoids overflow in int64_t maths)
 *
 * Using kΩ because MΩ values would lose precision in integer
 * division, and plain Ω would overflow even int64_t when
 * multiplied together.
 *
 * 180 MΩ = 180,000 kΩ
 * 400 MΩ = 400,000 kΩ
 * 2.74 MΩ = 2,740 kΩ
 */
#define ISO_R268_KR   180000   /* CELL_TOP to chassis (kΩ) */
#define ISO_R269_KR   180000   /* Chassis to GNDHV    (kΩ) */
#define ISO_R270_KR   400000   /* Chassis to div node (kΩ) */
#define ISO_R272_KR   2740     /* Div node to GNDHV   (kΩ) */

/* UN ECE R100 thresholds in Ω per volt of pack voltage.
 *
 * WARN: 500 Ω/V — UN R100 AC/combined system minimum.
 *       Below this, insulation is legally insufficient for
 *       an AC high-voltage system.
 *
 * FAULT: 100 Ω/V — UN R100 DC system absolute minimum.
 *        Below this, the vehicle must isolate the HV bus
 *        immediately.  This is also the post-crash minimum.
 */
#define ISO_WARN_OHM_PER_V   500
#define ISO_FAULT_OHM_PER_V  100

/* Practical early-warning threshold: 1 MΩ (1,000 kΩ).
 *
 * Healthy EV insulation is typically 10+ MΩ.  Anything
 * below 1 MΩ means something is starting to degrade,
 * even though it's still well above the legal minimums
 * for a 60V system.
 */
#define ISO_LOW_KR  1000


void board_measure_insulation(uint8_t        dev_id,
                              const int32_t  cell_mv[],
                              uint8_t        num_cells)
{
    int64_t  v_pack_mv;       /* Total pack voltage in mV          */
    int32_t  v_adc_mv;        /* Raw ADC reading from GPIO6 in mV  */
    int64_t  v_chassis_mv;    /* Back-calculated chassis voltage    */
    int64_t  v_expected_mv;   /* Expected V_pack / 2               */
    int64_t  deviation_mv;    /* How far off from expected          */
    int64_t  r_parallel_kr;   /* Parallel combo (R_bias || Rf)     */
    int64_t  r_fault_kr;      /* Calculated fault resistance (kΩ)  */
    int64_t  iso_floor_kr;    /* Measurement floor Rf (kΩ)         */
    int64_t  warn_kr;         /* Dynamic warning threshold (kΩ)    */
    int64_t  fault_kr;        /* Dynamic fault threshold (kΩ)      */
    uint8_t  saturated;       /* 1 = ADC in saturation region      */
    uint8_t  i;
    char     buf[128];
    const char *side;         /* "POS" or "NEG" for print          */
    const char *status;       /* "OK", "LOW", "WARNING", "FAULT"   */

    /* Initialise defaults */
    r_fault_kr   = 999999;    /* Assume healthy until proven otherwise */
    iso_floor_kr = 999999;
    saturated    = 0;
    side         = "---";

    /* ---- Step 1: Sum all cell voltages to get V_pack ----
     *
     * This is the total voltage across the battery stack.
     * For 16S Li-ion at 3.75V/cell, this is about 60,000 mV.
     */
    v_pack_mv = 0;

    for (i = 0; i < num_cells; i++)
    {
        v_pack_mv += cell_mv[i];
    }

    /* Sanity check — if pack voltage is unreasonably low,
     * the cells haven't been read yet.  Skip measurement. */
    if (v_pack_mv < 10000)
    {
        return;
    }

    /* ---- Step 2: Compute dynamic thresholds from V_pack ----
     *
     * UN R100 thresholds scale with pack voltage:
     *   threshold (kΩ) = Ω/V × V_pack(V) / 1000
     *
     * For 60V:   warn = 30 kΩ,   fault = 6 kΩ
     * For 120V:  warn = 60 kΩ,   fault = 12 kΩ
     * For 400V:  warn = 200 kΩ,  fault = 40 kΩ
     *
     * The practical early-warning threshold (1 MΩ = 1000 kΩ) is
     * used when it's higher than the R100 threshold, which is
     * always the case below ~2000V.
     */
    warn_kr  = (v_pack_mv / 1000) * ISO_WARN_OHM_PER_V / 1000;
    fault_kr = (v_pack_mv / 1000) * ISO_FAULT_OHM_PER_V / 1000;

    /* Use the higher of UN R100 or practical threshold */
    if (warn_kr < ISO_LOW_KR)
    {
        warn_kr = ISO_LOW_KR;
    }

    /* ---- Step 3: Read GPIO6 ADC (insulation divider output) ----
     *
     * bq79616_analog_read() returns the latest value from the
     * continuous round-robin cycle.  No new conversion is
     * triggered — it just reads the register.
     *
     * Returns millivolts, or -1 on error.
     */
    v_adc_mv = bq79616_analog_read(dev_id, 6);

    if (v_adc_mv < 0)
    {
        board_dbg("ISO: GPIO6 ADC read failed\r\n");
        return;
    }

    /* ---- Step 4: Back-calculate chassis voltage ----
     *
     * The R270/R272 divider scales chassis voltage down to
     * the ADC range.  To get the actual chassis voltage
     * (relative to GNDHV), we reverse the divider equation:
     *
     *   V_adc = V_chassis × R272 / (R270 + R272)
     *
     * Therefore:
     *   V_chassis = V_adc × (R270 + R272) / R272
     */
    v_chassis_mv = (int64_t)v_adc_mv
                 * (ISO_R270_KR + ISO_R272_KR)
                 / ISO_R272_KR;

    /* ---- Step 5: Compare to expected midpoint ---- */
    v_expected_mv = v_pack_mv / 2;
    deviation_mv  = v_chassis_mv - v_expected_mv;

    /* ---- Step 6: Determine measurement floor ----
     *
     * The 180 MΩ bias resistors are enormous compared to any
     * realistic fault resistance.  Even a 1 MΩ fault is 180×
     * smaller than R268/R269, so the chassis voltage slams to
     * nearly 0V or V_pack and the ADC saturates.
     *
     * The "measurement floor" is the fault resistance below
     * which the ADC is in the saturation zone and the Rf
     * formula gives unreliable results.  We compute this by
     * finding the Rf that produces exactly 170% of the
     * expected ADC midpoint.
     *
     * When the ADC is saturated, we report "Rf < floor"
     * because we know insulation is degraded but can't
     * measure exactly how much.  The classification still
     * runs on the floor value — for a 60V pack, the floor
     * is ~35 MΩ which is miles above the UN R100 legal
     * minimum (30 kΩ), so saturated readings classify as
     * "LOW" (degraded but legally safe), not "FAULT".
     *
     * Expected ADC = V_pack × R272 / (2 × (R270 + R272))
     *
     * For 60V:  midpoint ≈ 220 mV
     *           30% boundary ≈ 66 mV   (saturated NEG)
     *           170% boundary ≈ 374 mV (saturated POS)
     *           Rf at boundary ≈ 35 MΩ
     */
    {
        int64_t v_adc_mid;     /* Expected healthy ADC midpoint (mV) */
        int64_t adc_low;       /* Below this = saturated NEG         */
        int64_t adc_high;      /* Above this = saturated POS         */
        int64_t v_ch_at_bnd;   /* Chassis voltage at boundary        */
        int64_t r_par_bnd;     /* r_parallel at boundary             */

        v_adc_mid = v_pack_mv * ISO_R272_KR
                  / (2 * ((int64_t)ISO_R270_KR + ISO_R272_KR));

        adc_low  = v_adc_mid * 30 / 100;    /* 30% of expected  */
        adc_high = v_adc_mid * 170 / 100;    /* 170% of expected */

        /* Compute floor Rf from the high boundary (POS side).
         * Back-calculate chassis voltage at the 170% boundary,
         * then run the normal Rf formula on it.  The floor is
         * the same for POS and NEG because R268 = R269. */
        v_ch_at_bnd = adc_high
                    * ((int64_t)ISO_R270_KR + ISO_R272_KR)
                    / ISO_R272_KR;

        if ((v_ch_at_bnd > 0) && (v_ch_at_bnd < v_pack_mv))
        {
            r_par_bnd = (int64_t)ISO_R269_KR
                      * (v_pack_mv - v_ch_at_bnd)
                      / v_ch_at_bnd;

            if (r_par_bnd < ISO_R268_KR)
            {
                iso_floor_kr = r_par_bnd * ISO_R268_KR
                             / (ISO_R268_KR - r_par_bnd);
            }
        }

        /* Check if ADC is in the saturated region */
        if ((int64_t)v_adc_mv < adc_low)
        {
            saturated = 1;
            side      = "NEG";
        }
        else if ((int64_t)v_adc_mv > adc_high)
        {
            saturated = 1;
            side      = "POS";
        }
    }

    /* ---- Step 7: Compute fault resistance ----
     *
     * If the ADC is saturated, we already know the side and
     * Rf is somewhere below the measurement floor.  Skip
     * the formula (it gives garbage in saturation) and use
     * the floor as Rf for classification purposes.
     *
     * If the ADC is in the measurable range, run the normal
     * formula to compute an accurate Rf.
     */
    if (saturated)
    {
        /* Use the floor for classification.
         * We'll print "Rf<floor" to show it's an upper bound. */
        r_fault_kr = iso_floor_kr;
    }
    else if (deviation_mv > 0)
    {
        /* ----- POSITIVE-SIDE fault: chassis toward B+ -----
         *
         * Rf from CELL_TOP to chassis, in parallel with R268.
         *
         * R_top_eff = R269 × (V_pack - V_chassis) / V_chassis
         * Rf = R_top_eff × R268 / (R268 - R_top_eff)
         */
        side = "POS";

        r_parallel_kr = (int64_t)ISO_R269_KR
                      * (v_pack_mv - v_chassis_mv)
                      / v_chassis_mv;

        if (r_parallel_kr >= ISO_R268_KR)
        {
            r_fault_kr = 999999;   /* Noise, effectively infinite */
        }
        else
        {
            r_fault_kr = r_parallel_kr * ISO_R268_KR
                       / (ISO_R268_KR - r_parallel_kr);
        }
    }
    else if (deviation_mv < 0)
    {
        /* ----- NEGATIVE-SIDE fault: chassis toward B- -----
         *
         * Rf from GNDHV to chassis, in parallel with R269.
         *
         * R_bot_eff = R268 × V_chassis / (V_pack - V_chassis)
         * Rf = R_bot_eff × R269 / (R269 - R_bot_eff)
         */
        side = "NEG";

        r_parallel_kr = (int64_t)ISO_R268_KR
                      * v_chassis_mv
                      / (v_pack_mv - v_chassis_mv);

        if (r_parallel_kr >= ISO_R269_KR)
        {
            r_fault_kr = 999999;   /* Noise, effectively infinite */
        }
        else
        {
            r_fault_kr = r_parallel_kr * ISO_R269_KR
                       / (ISO_R269_KR - r_parallel_kr);
        }
    }
    /* else: deviation == 0, r_fault_kr stays 999999 (healthy) */

    /* ---- Step 8: Classify against thresholds ----
     *
     * Status levels (from healthy to dangerous):
     *
     *   OK      — Rf > warn_kr   (healthy, typically > 1 MΩ)
     *   LOW     — Rf > fault_kr  (degrading, schedule service)
     *   WARNING — Rf > 0         (below warn, above fault)
     *   FAULT   — Rf ≤ fault_kr  (UN R100 100 Ω/V breached)
     *
     * Thresholds are voltage-dependent (computed in Step 2),
     * so daisy-chaining boards for higher V_pack automatically
     * raises the thresholds:
     *
     *   V_pack    warn_kr      fault_kr
     *   ------    ----------   ----------
     *    60V      1000 kΩ       6 kΩ
     *   120V      1000 kΩ      12 kΩ
     *   400V      1000 kΩ      40 kΩ
     *   800V      1000 kΩ      80 kΩ
     */
    if (r_fault_kr > warn_kr)
    {
        status = "OK";
    }
    else if (r_fault_kr > fault_kr)
    {
        status = "LOW";
    }
    else if (r_fault_kr > 0)
    {
        status = "WARNING";
    }
    else
    {
        status = "FAULT";
    }

    /* ---- Step 9: Print result ----
     *
     * Always show: status, side, Rf, and raw ADC mV.
     *
     * When saturated: "Rf<floor" (upper bound, exact Rf unknown)
     * When measurable: "Rf=value" (accurate computed value)
     * When infinite: "Rf>1000 MR" (no measurable fault)
     *
     * Rf shown in both MΩ and kΩ so the user can see the
     * resolution at any scale.
     *
     * Examples at 60V (floor ≈ 35 MΩ):
     *   ISO: OK      ---  Rf>1000 MR         adc=204 mV
     *   ISO: OK      NEG  Rf=200 MR (200000) adc=199 mV
     *   ISO: LOW     POS  Rf<35 MR (35000)   adc=469 mV
     *   ISO: LOW     NEG  Rf<35 MR (35000)   adc=49 mV
     */
    if (saturated)
    {
        /* Saturated: Rf is below the measurement floor.
         * Show floor in MΩ with kΩ in parentheses. */
        snprintf(iso_line_buf, sizeof(iso_line_buf),
                 "ISO: %-7s %s  Rf<%ld MR (%ld)  adc=%ld mV",
                 status, side,
                 (long)(iso_floor_kr / 1000),
                 (long)iso_floor_kr,
                 (long)v_adc_mv);
    }
    else if (r_fault_kr > 99999)
    {
        /* Effectively infinite — no measurable fault */
        snprintf(iso_line_buf, sizeof(iso_line_buf),
                 "ISO: %-7s %s  Rf>1000 MR  adc=%ld mV",
                 status, side, (long)v_adc_mv);
    }
    else
    {
        /* Measurable Rf — show in MΩ with kΩ in parentheses */
        snprintf(iso_line_buf, sizeof(iso_line_buf),
                 "ISO: %-7s %s  Rf=%ld MR (%ld)  adc=%ld mV",
                 status, side,
                 (long)(r_fault_kr / 1000),
                 (long)r_fault_kr,
                 (long)v_adc_mv);
    }

    /* Print to debug terminal (only visible when sys_debug=true) */
    snprintf(buf, sizeof(buf), "%s\r\n", iso_line_buf);
    board_dbg(buf);
}


/* ===============================================================
 *  NTC Thermistor Temperature Measurement
 *
 *  Reads NTC thermistors connected to BQ79616 GPIO pins via the
 *  TSREF voltage divider circuit:
 *
 *    TSREF (5V) --- R_FIXED (10kΩ) ---+--- NTC (10kΩ@25°C) --- GNDHV
 *                                       |
 *                                R_FILT (1kΩ) + C_FILT (100nF)
 *                                       |
 *                                   GPIO pin (ADC)
 *
 *  The NTC is a Murata NCP18XH103F03RB:
 *    - 10 kΩ at 25°C (±1%)
 *    - B25/50 = 3380 K (±1%)
 *    - 0603 package, -40°C to +125°C range
 *
 *  HOW IT WORKS:
 *    As the NTC gets hotter, its resistance drops.  This pulls
 *    the voltage divider midpoint lower, so the ADC reads a
 *    lower voltage.  We reverse the maths to get temperature:
 *
 *    Step 1: V_adc → R_ntc  (from the voltage divider equation)
 *    Step 2: R_ntc → Temp   (from the NTC Beta equation)
 *
 *  The "Beta equation" is the standard way to convert NTC
 *  resistance to temperature.  It's like the NTC's version of
 *  Ohm's law:
 *
 *    1/T = 1/T0 + (1/B) × ln(R_ntc / R0)
 *
 *  Where T0 and R0 are the reference point (25°C = 298.15K,
 *  10 kΩ), B is the Beta constant (3380K), and T is in Kelvin.
 *
 *  Pin assignments:
 *    GPIO5 = Balance board temperature (one sensor)
 *    GPIO1 = Battery temperature sensor 1
 *    GPIO2 = Battery temperature sensor 2
 *    GPIO3 = Battery temperature sensor 3
 *    GPIO4 = Battery temperature sensor 4
 *
 *  All five circuits are wired identically.
 * =============================================================== */

/* ----- NTC circuit constants -----
 *
 * These match the schematic values.  If you change the
 * NTC part or resistors, update these defines.
 */
#define NTC_TSREF_MV   5000     /* TSREF LDO output voltage (mV)  */
#define NTC_R_FIXED    10000    /* Series resistor R104 (ohms)     */
#define NTC_R_NOM      10000    /* NTC resistance at 25°C (ohms)   */
#define NTC_BETA       3380     /* Beta constant B25/50 (Kelvin)   */
#define NTC_T_NOM_K    298.15f  /* 25°C in Kelvin                  */

/* Error sentinel — returned when the reading is invalid.
 * -99°C is clearly impossible for a battery/board temperature,
 * so the caller can check for this value. */
#define NTC_ERROR_C    (-99)


/* ---------------------------------------------------------------
 *  ntc_adc_to_temp_c  –  Convert an ADC millivolt reading to °C
 *
 *  This is the core maths function used by both the balance
 *  temp and battery temp functions.  It's "static" so it's
 *  only visible inside board.c (like a private helper).
 *
 *  Parameters:
 *    v_adc_mv – voltage at the divider midpoint in millivolts
 *               (as returned by bq79616_analog_read)
 *
 *  Returns:
 *    Temperature in degrees Celsius (whole number), or
 *    NTC_ERROR_C (-99) if the reading is invalid.
 *
 *  Uses floating point (STM32F4 has a hardware FPU, so this
 *  is fast — takes about 2 microseconds per call).
 * --------------------------------------------------------------- */
static int16_t ntc_adc_to_temp_c(int32_t v_adc_mv)
{
    float r_ntc;       /* NTC resistance in ohms              */
    float t_kelvin;    /* Temperature in Kelvin               */
    float t_celsius;   /* Temperature in degrees Celsius      */

    /* Guard: ADC must be between 1 mV and (TSREF - 1 mV).
     *
     * V_adc = 0 means NTC is open circuit (disconnected).
     * V_adc >= TSREF means NTC is short circuit (damaged).
     * Both are hardware faults, not valid temperatures. */
    if ((v_adc_mv <= 0) || (v_adc_mv >= NTC_TSREF_MV))
    {
        return NTC_ERROR_C;
    }

    /* Step 1: Calculate NTC resistance from voltage divider.
     *
     * The circuit is: TSREF → R_FIXED → midpoint → R_NTC → GND
     *
     * Voltage divider equation:
     *   V_adc = TSREF × R_ntc / (R_fixed + R_ntc)
     *
     * Rearranging for R_ntc:
     *   R_ntc = R_fixed × V_adc / (TSREF - V_adc)
     *
     * Example at 25°C: R_ntc = 10000 × 2500 / (5000 - 2500)
     *                        = 10000 Ω  ✓
     */
    r_ntc = (float)NTC_R_FIXED
          * (float)v_adc_mv
          / (float)(NTC_TSREF_MV - v_adc_mv);

    /* Guard: R_ntc must be positive (already guaranteed by
     * the range check above, but belt-and-braces). */
    if (r_ntc <= 0.0f)
    {
        return NTC_ERROR_C;
    }

    /* Step 2: Convert resistance to temperature using the
     * NTC Beta equation.
     *
     *   1/T = 1/T0 + (1/B) × ln(R_ntc / R0)
     *
     * Where:
     *   T0  = 298.15 K  (25°C, the NTC's reference temperature)
     *   R0  = 10000 Ω   (NTC resistance at T0)
     *   B   = 3380 K    (Beta constant from the datasheet)
     *   ln  = natural logarithm
     *   T   = result in Kelvin
     *
     * Then convert Kelvin to Celsius: T_C = T_K - 273.15
     *
     * Example at 25°C:
     *   ln(10000/10000) = ln(1) = 0
     *   1/T = 1/298.15 + 0 = 1/298.15
     *   T = 298.15 K = 25.0°C  ✓
     *
     * Example at 50°C (R_ntc ≈ 4160 Ω):
     *   ln(4160/10000) = -0.876
     *   1/T = 1/298.15 + (1/3380) × (-0.876)
     *       = 0.003354 - 0.000259 = 0.003095
     *   T = 1/0.003095 = 323.1 K = 49.9°C  ✓
     */
    t_kelvin = 1.0f / (  (1.0f / NTC_T_NOM_K)
                        + (1.0f / (float)NTC_BETA)
                          * logf(r_ntc / (float)NTC_R_NOM)  );

    t_celsius = t_kelvin - 273.15f;

    /* Sanity check — if temperature is wildly out of range,
     * something is wrong with the hardware.  The NTC is rated
     * -40°C to +125°C. */
    if ((t_celsius < -40.0f) || (t_celsius > 125.0f))
    {
        return NTC_ERROR_C;
    }

    /* Round to nearest integer.
     * Adding 0.5 before truncating gives proper rounding:
     *   24.6 + 0.5 = 25.1 → (int16_t) = 25
     *   24.4 + 0.5 = 24.9 → (int16_t) = 24
     * For negative values, subtract 0.5 instead. */
    if (t_celsius >= 0.0f)
    {
        return (int16_t)(t_celsius + 0.5f);
    }
    else
    {
        return (int16_t)(t_celsius - 0.5f);
    }
}


/* ---------------------------------------------------------------
 *  board_get_balance_temp  –  Read the balance board temperature
 *
 *  Reads the NTC on GPIO5 and prints the temperature to the
 *  debug terminal.
 *
 *  Parameters:
 *    dev_id – BQ79616 device address (0x01)
 *
 *  Returns:
 *    Temperature in °C, or NTC_ERROR_C (-99) on failure.
 *
 *  Called from application.c in the 5-second periodic block.
 * --------------------------------------------------------------- */
int16_t board_get_balance_temp(uint8_t dev_id)
{
    int32_t  v_adc_mv;    /* Raw ADC reading from GPIO5 (mV) */
    int16_t  temp_c;      /* Converted temperature (°C)      */
    char     buf[64];

    /* Read GPIO5 — the latest value from the continuous
     * round-robin ADC.  No UART traffic is generated by
     * reading a different GPIO than cell voltages. */
    v_adc_mv = bq79616_analog_read(dev_id, 5);

    if (v_adc_mv < 0)
    {
        board_dbg("BAL TEMP: read failed\r\n");
        return NTC_ERROR_C;
    }

    /* Convert millivolts to degrees Celsius */
    temp_c = ntc_adc_to_temp_c(v_adc_mv);

    if (temp_c == NTC_ERROR_C)
    {
        snprintf(bal_temp_line_buf, sizeof(bal_temp_line_buf),
                 "BAL TEMP: ERROR  adc=%ld mV",
                 (long)v_adc_mv);
    }
    else
    {
        snprintf(bal_temp_line_buf, sizeof(bal_temp_line_buf),
                 "BAL TEMP: %d C  adc=%ld mV",
                 (int)temp_c, (long)v_adc_mv);
    }

    /* Print to debug terminal (only when sys_debug=true) */
    snprintf(buf, sizeof(buf), "%s\r\n", bal_temp_line_buf);
    board_dbg(buf);
    return temp_c;
}


/* ---------------------------------------------------------------
 *  board_get_battery_temps  –  Read all four battery temperature
 *                               sensors
 *
 *  Reads the NTCs on GPIO1 through GPIO4, converts each to °C,
 *  fills the output array, and prints all four readings on one
 *  line.
 *
 *  Parameters:
 *    dev_id    – BQ79616 device address (0x01)
 *    temps_out – array of at least 4 int16_t to receive the
 *                temperatures (°C).  Failed readings get
 *                NTC_ERROR_C (-99).
 *
 *  Called from application.c in the 5-second periodic block.
 * --------------------------------------------------------------- */
void board_get_battery_temps(uint8_t dev_id, int16_t temps_out[4])
{
    int32_t  v_adc_mv;    /* Raw ADC reading (mV)      */
    int      pos;
    uint8_t  pin;         /* GPIO pin number (1 to 4)  */

    /* Build the output line into the static buffer */
    pos = snprintf(batt_temp_line_buf, sizeof(batt_temp_line_buf),
                   "BATT TEMP:");

    for (pin = 1; pin <= 4; pin++)
    {
        /* Read this GPIO's ADC value */
        v_adc_mv = bq79616_analog_read(dev_id, pin);

        if (v_adc_mv < 0)
        {
            /* Comms failure — couldn't read the register */
            temps_out[pin - 1] = NTC_ERROR_C;

            pos += snprintf(&batt_temp_line_buf[pos],
                            sizeof(batt_temp_line_buf) - (size_t)pos,
                            "  T%d=ERR", (int)pin);
        }
        else
        {
            /* Convert millivolts to degrees Celsius */
            temps_out[pin - 1] = ntc_adc_to_temp_c(v_adc_mv);

            if (temps_out[pin - 1] == NTC_ERROR_C)
            {
                pos += snprintf(&batt_temp_line_buf[pos],
                                sizeof(batt_temp_line_buf) - (size_t)pos,
                                "  T%d=ERR(%ld)",
                                (int)pin, (long)v_adc_mv);
            }
            else
            {
                pos += snprintf(&batt_temp_line_buf[pos],
                                sizeof(batt_temp_line_buf) - (size_t)pos,
                                "  T%d=%d",
                                (int)pin,
                                (int)temps_out[pin - 1]);
            }
        }
    }

    /* Append units */
    pos += snprintf(&batt_temp_line_buf[pos],
                    sizeof(batt_temp_line_buf) - (size_t)pos,
                    " C");

    /* Clamp to buffer size (safety) */
    if (pos >= (int)sizeof(batt_temp_line_buf))
    {
        pos = (int)sizeof(batt_temp_line_buf) - 1;
    }

    /* Print to debug terminal (only when sys_debug=true) */
    {
        char dbg_line[100];
        snprintf(dbg_line, sizeof(dbg_line), "%s\r\n",
                 batt_temp_line_buf);
        board_dbg(dbg_line);
    }
}
/* ================================================================
 *  FDCAN1 (Control Bus) — heartbeat TX and RX
 *
 *  ---- CubeMX changes required ----
 *
 *  Both FDCAN1 and FDCAN2 need these settings changed from
 *  the defaults before generating code:
 *
 *  Connectivity → FDCAN1 (and FDCAN2):
 *    NominalPrescaler     = 8    (was 16)
 *    NominalTimeSeg1      = 13   (was 1)
 *    NominalTimeSeg2      = 2    (was 1)
 *    NominalSyncJumpWidth = 2    (was 1)
 *    AutoRetransmission   = ENABLE (was DISABLE)
 *    FDCAN1 StdFiltersNbr = 1    (was 0)
 *    FDCAN2 StdFiltersNbr = 3    (heartbeat + cells + balance)
 *
 *  Calculation:
 *    64 MHz / 8 = 8 MHz time quantum
 *    Bit time = 1 + 13 + 2 = 16 quanta
 *    Baud = 8 MHz / 16 = 500 kbit/s
 *    Sample point = (1+13)/16 = 87.5% (automotive standard)
 *
 *  AutoRetransmission MUST be ENABLE — CAN protocol requires
 *  retransmission on arbitration loss or error.  Without it,
 *  frames are silently dropped on any bus collision.
 *
 *  StdFiltersNbr MUST be >= 1 — the HAL allocates message RAM
 *  filter slots at init time.  With 0 filters, no messages can
 *  ever be received (all are rejected by hardware).
 *
 *  NVIC:
 *    No interrupt changes needed for polling mode.  Interrupts
 *    can be added later for FIFO watermark or TX complete.
 * ================================================================ */

/* Heartbeat CAN ID base — each board adds its address (0–7).
 * Board 0 sends 0x1B0, Board 3 sends 0x1B3, etc. */
#define CAN_ID_HEARTBEAT_BASE  0x1B0U
#define CAN2_ID_CELLS_BASE     0x200U
#define CAN2_ID_CELLS_LAST     0x237U
#define CAN2_CELL_FRAME_STEP   0x10U
#define CAN2_CELL_FRAMES       4U
#define CAN2_CELLS_PER_FRAME   4U
#define CAN2_ID_BAL_STATUS_BASE 0x400U
#define CAN2_ID_BAL_CMD_BASE    0x410U
#define CAN2_ID_BAL_LAST        0x417U

/* Rolling counter — increments 0..255 per heartbeat sent.
 * Receivers use this to detect missed messages. */
static uint8_t hb1_rolling_counter = 0;
static uint8_t hb2_rolling_counter = 0;
static uint8_t bal2_status_counter = 0;
static uint8_t bal2_cmd_counter    = 0;

static bool board_can_init_bus(FDCAN_HandleTypeDef *hfdcan,
                               const char          *name)
{
    FDCAN_FilterTypeDef filter;
    char                buf[64];

    filter.IdType       = FDCAN_STANDARD_ID;
    filter.FilterIndex  = 0;
    filter.FilterType   = FDCAN_FILTER_MASK;
    filter.FilterConfig = FDCAN_FILTER_TO_RXFIFO0;
    filter.FilterID1    = CAN_ID_HEARTBEAT_BASE;
    filter.FilterID2    = 0x7F8U;

    if (HAL_FDCAN_ConfigFilter(hfdcan, &filter) != HAL_OK)
    {
        snprintf(buf, sizeof(buf), "%s: filter config FAILED\r\n", name);
        board_dbg(buf);
        return false;
    }

    if (HAL_FDCAN_ConfigGlobalFilter(hfdcan,
                                     FDCAN_REJECT,
                                     FDCAN_REJECT,
                                     FDCAN_REJECT_REMOTE,
                                     FDCAN_REJECT_REMOTE) != HAL_OK)
    {
        snprintf(buf, sizeof(buf), "%s: global filter FAILED\r\n", name);
        board_dbg(buf);
        return false;
    }

    if (HAL_FDCAN_Start(hfdcan) != HAL_OK)
    {
        snprintf(buf, sizeof(buf), "%s: start FAILED\r\n", name);
        board_dbg(buf);
        return false;
    }

    snprintf(buf, sizeof(buf),
             "%s: started, 500 kbit/s, filter 0x1B0-0x1B7\r\n",
             name);
    board_dbg(buf);
    return true;
}

static bool board_can2_init_bus(void)
{
    FDCAN_FilterTypeDef filter;
    char                buf[80];

    filter.IdType       = FDCAN_STANDARD_ID;
    filter.FilterType   = FDCAN_FILTER_MASK;
    filter.FilterConfig = FDCAN_FILTER_TO_RXFIFO0;
    filter.FilterIndex  = 0;
    filter.FilterID1    = CAN_ID_HEARTBEAT_BASE;
    filter.FilterID2    = 0x7F8U;

    if (HAL_FDCAN_ConfigFilter(&hfdcan2, &filter) != HAL_OK)
    {
        board_dbg("CAN2: heartbeat filter config FAILED\r\n");
        return false;
    }

    filter.FilterType   = FDCAN_FILTER_RANGE;
    filter.FilterIndex  = 1;
    filter.FilterID1    = CAN2_ID_CELLS_BASE;
    filter.FilterID2    = CAN2_ID_CELLS_LAST;

    if (HAL_FDCAN_ConfigFilter(&hfdcan2, &filter) != HAL_OK)
    {
        board_dbg("CAN2: cell filter config FAILED\r\n");
        return false;
    }

    filter.FilterIndex  = 2;
    filter.FilterID1    = CAN2_ID_BAL_STATUS_BASE;
    filter.FilterID2    = CAN2_ID_BAL_LAST;

    if (HAL_FDCAN_ConfigFilter(&hfdcan2, &filter) != HAL_OK)
    {
        board_dbg("CAN2: balance filter config FAILED\r\n");
        return false;
    }

    if (HAL_FDCAN_ConfigGlobalFilter(&hfdcan2,
                                     FDCAN_REJECT,
                                     FDCAN_REJECT,
                                     FDCAN_REJECT_REMOTE,
                                     FDCAN_REJECT_REMOTE) != HAL_OK)
    {
        board_dbg("CAN2: global filter FAILED\r\n");
        return false;
    }

    if (HAL_FDCAN_Start(&hfdcan2) != HAL_OK)
    {
        board_dbg("CAN2: start FAILED\r\n");
        return false;
    }

    snprintf(buf, sizeof(buf),
             "CAN2: started, 500 kbit/s, filters 0x1B0-0x1B7 + 0x200-0x237 + 0x400-0x417\r\n");
    board_dbg(buf);
    return true;
}

static bool board_can_tx_standard_frame(FDCAN_HandleTypeDef *hfdcan,
                                        uint32_t             std_id,
                                        uint8_t              tx_data[8])
{
    FDCAN_TxHeaderTypeDef tx_header;

    tx_header.Identifier          = std_id;
    tx_header.IdType              = FDCAN_STANDARD_ID;
    tx_header.TxFrameType         = FDCAN_DATA_FRAME;
    tx_header.DataLength          = FDCAN_DLC_BYTES_8;
    tx_header.ErrorStateIndicator = FDCAN_ESI_ACTIVE;
    tx_header.BitRateSwitch       = FDCAN_BRS_OFF;
    tx_header.FDFormat            = FDCAN_CLASSIC_CAN;
    tx_header.TxEventFifoControl  = FDCAN_NO_TX_EVENTS;
    tx_header.MessageMarker       = 0;

    if (HAL_FDCAN_AddMessageToTxFifoQ(hfdcan,
                                      &tx_header,
                                      tx_data) != HAL_OK)
    {
        return false;
    }

    return true;
}

static bool board_can_tx_heartbeat_bus(FDCAN_HandleTypeDef *hfdcan,
                                       uint8_t             *rolling_counter,
                                       int32_t              min_cell_mv,
                                       int32_t              max_cell_mv,
                                       uint8_t              cell_count,
                                       uint8_t              state)
{
    uint8_t               tx_data[8];
    uint8_t               addr = board_get_address();

    tx_data[0] = addr;
    tx_data[1] = state;
    tx_data[2] = cell_count;

    {
        uint16_t min_mv = (min_cell_mv > 0)
                          ? (uint16_t)min_cell_mv : 0U;
        tx_data[3] = (uint8_t)(min_mv >> 8);
        tx_data[4] = (uint8_t)(min_mv & 0xFF);
    }

    {
        uint16_t max_mv = (max_cell_mv > 0)
                          ? (uint16_t)max_cell_mv : 0U;
        tx_data[5] = (uint8_t)(max_mv >> 8);
        tx_data[6] = (uint8_t)(max_mv & 0xFF);
    }

    tx_data[7] = *rolling_counter;
    (*rolling_counter)++;

    return board_can_tx_standard_frame(hfdcan,
                                       CAN_ID_HEARTBEAT_BASE
                                       + (uint32_t)addr,
                                       tx_data);
}

static bool board_can_rx_message_bus(FDCAN_HandleTypeDef *hfdcan,
                                     uint32_t            *std_id,
                                     uint8_t              rx_data[8])
{
    FDCAN_RxHeaderTypeDef rx_header;

    if (HAL_FDCAN_GetRxFifoFillLevel(hfdcan, FDCAN_RX_FIFO0) == 0)
    {
        return false;
    }

    if (HAL_FDCAN_GetRxMessage(hfdcan,
                               FDCAN_RX_FIFO0,
                               &rx_header,
                               rx_data) != HAL_OK)
    {
        return false;
    }

    if (rx_header.IdType != FDCAN_STANDARD_ID ||
        rx_header.RxFrameType != FDCAN_DATA_FRAME ||
        rx_header.DataLength != FDCAN_DLC_BYTES_8)
    {
        return false;
    }

    if (std_id != NULL)
    {
        *std_id = rx_header.Identifier;
    }

    return true;
}

static int8_t board_can_rx_heartbeat_bus(FDCAN_HandleTypeDef *hfdcan,
                                         uint8_t              rx_data[8])
{
    uint32_t sender_id;

    if (!board_can_rx_message_bus(hfdcan, &sender_id, rx_data))
    {
        return -1;
    }

    if ((sender_id < CAN_ID_HEARTBEAT_BASE) ||
        (sender_id > (CAN_ID_HEARTBEAT_BASE + 7U)))
    {
        return -1;
    }

    sender_id -= CAN_ID_HEARTBEAT_BASE;
    return (int8_t)sender_id;
}


/* ================================================================
 * board_can_init()
 *
 * Configure FDCAN1 for the control bus:
 *   1. Set up one RX filter to accept heartbeat IDs (0x1B0–0x1B7)
 *   2. Start the FDCAN peripheral
 *
 * Must be called AFTER CubeMX's MX_FDCAN1_Init() has already
 * configured the timing, mode, and allocated filter RAM.
 *
 * The filter uses mask mode:
 *   FilterID1 = 0x1B0  (the pattern to match)
 *   FilterID2 = 0x7F8  (mask — bits that must match)
 *
 *   0x1B0 = 0b 0001 1011 0000
 *   0x7F8 = 0b 0111 1111 1000  (bottom 3 bits are don't-care)
 *
 *   This accepts IDs 0x1B0 through 0x1B7 — exactly the 8
 *   possible board heartbeat IDs.  Everything else is rejected
 *   by hardware, so the RX FIFO never fills with irrelevant
 *   traffic from a motor controller or charger.
 *
 * Returns true if FDCAN started successfully.
 * ================================================================ */
bool board_can_init(void)
{
    return board_can_init_bus(&hfdcan1, "CAN1");
}

bool board_can2_init(void)
{
    return board_can2_init_bus();
}
#if 0
     *
     * FilterType = MASK means:
     *   "Accept any ID where (received_ID & FilterID2) == FilterID1"
     *
     * FilterID1 = 0x1B0 (pattern)
     * FilterID2 = 0x7F8 (mask — bottom 3 bits don't-care)
     *
     * Matches: 0x1B0, 0x1B1, 0x1B2 ... 0x1B7
     * Rejects: everything else */
    filter.IdType       = FDCAN_STANDARD_ID;
    filter.FilterIndex  = 0;                 /* First (and only) filter */
    filter.FilterType   = FDCAN_FILTER_MASK; /* ID + mask mode          */
    filter.FilterConfig = FDCAN_FILTER_TO_RXFIFO0; /* Route to FIFO 0  */
    filter.FilterID1    = CAN_ID_HEARTBEAT_BASE;   /* 0x1B0            */
    filter.FilterID2    = 0x7F8U;                   /* Mask             */

    if (HAL_FDCAN_ConfigFilter(&hfdcan1, &filter) != HAL_OK)
    {
        board_dbg("CAN: filter config FAILED\r\n");
        return false;
    }

    /* Reject all non-matching standard IDs and all extended IDs.
     * Without this, non-matching frames go to FIFO 0 by default
     * on some STM32 families, filling it with junk. */
    if (HAL_FDCAN_ConfigGlobalFilter(&hfdcan1,
                                     FDCAN_REJECT,   /* non-match std */
                                     FDCAN_REJECT,   /* non-match ext */
                                     FDCAN_REJECT_REMOTE,
                                     FDCAN_REJECT_REMOTE) != HAL_OK)
    {
        board_dbg("CAN: global filter FAILED\r\n");
        return false;
    }

    /* ---- Start the FDCAN peripheral ----
     *
     * After this call, the transceiver is active on the bus.
     * TX frames can be queued, and matching RX frames will
     * appear in FIFO 0. */
    if (HAL_FDCAN_Start(&hfdcan1) != HAL_OK)
    {
        board_dbg("CAN: start FAILED\r\n");
        return false;
    }

    board_dbg("CAN: FDCAN1 started, 500 kbit/s, "
              "filter 0x1B0-0x1B7\r\n");
    return true;
}
#endif


/* ================================================================
 * board_can_tx_heartbeat()
 *
 * Build and transmit a heartbeat frame on FDCAN1.
 *
 * Frame layout (from BMS_CANBUS_Architecture.md):
 *   Byte 0   : Board ID (0–7)
 *   Byte 1   : Board state (0=OK, 1=Warning, 2=Fault)
 *   Byte 2   : Active cell count (6–16)
 *   Byte 3   : Min cell voltage high byte (mV, big-endian)
 *   Byte 4   : Min cell voltage low byte
 *   Byte 5   : Max cell voltage high byte (mV, big-endian)
 *   Byte 6   : Max cell voltage low byte
 *   Byte 7   : Rolling counter (0–255, wraps)
 *
 * CAN ID = 0x1B0 + board_address.
 *
 * Returns true if the frame was queued in the TX FIFO.
 * Returns false if the TX FIFO is full (bus error or
 * no other node ACKing — common when testing with one board).
 * ================================================================ */
bool board_can_tx_heartbeat(int32_t  min_cell_mv,
                            int32_t  max_cell_mv,
                            uint8_t  cell_count,
                            uint8_t  state)
{
    return board_can_tx_heartbeat_bus(&hfdcan1,
                                      &hb1_rolling_counter,
                                      min_cell_mv,
                                      max_cell_mv,
                                      cell_count,
                                      state);
}

bool board_can2_tx_heartbeat(int32_t  min_cell_mv,
                             int32_t  max_cell_mv,
                             uint8_t  cell_count,
                             uint8_t  state)
{
    return board_can_tx_heartbeat_bus(&hfdcan2,
                                      &hb2_rolling_counter,
                                      min_cell_mv,
                                      max_cell_mv,
                                      cell_count,
                                      state);
}

bool board_can2_tx_has_free_slot(void)
{
    return (HAL_FDCAN_GetTxFifoFreeLevel(&hfdcan2) > 0U);
}

bool board_can2_tx_cell_voltage_frame(const int32_t cell_mv[],
                                      uint8_t       cell_count,
                                      uint8_t       frame_index)
{
    uint8_t addr = board_get_address();
    uint8_t tx_data[8];
    uint8_t slot;

    if (frame_index >= CAN2_CELL_FRAMES)
    {
        return false;
    }

    memset(tx_data, 0, sizeof(tx_data));

    for (slot = 0; slot < CAN2_CELLS_PER_FRAME; slot++)
    {
        uint8_t  cell_index = (uint8_t)(frame_index * CAN2_CELLS_PER_FRAME
                                        + slot);
        uint16_t mv = 0U;

        if (cell_mv != NULL && cell_index < cell_count)
        {
            int32_t raw_mv = cell_mv[cell_index];
            if (raw_mv > 0)
            {
                mv = (uint16_t)raw_mv;
            }
        }

        tx_data[slot * 2U]     = (uint8_t)(mv >> 8);
        tx_data[slot * 2U + 1] = (uint8_t)(mv & 0xFF);
    }

    return board_can_tx_standard_frame(&hfdcan2,
                                       CAN2_ID_CELLS_BASE
                                       + ((uint32_t)frame_index
                                          * CAN2_CELL_FRAME_STEP)
                                       + (uint32_t)addr,
                                       tx_data);
}

bool board_can2_tx_cell_voltages(const int32_t cell_mv[],
                                 uint8_t       cell_count)
{
    uint8_t  frame;
    bool     all_ok = true;

    for (frame = 0; frame < CAN2_CELL_FRAMES; frame++)
    {
        if (!board_can2_tx_cell_voltage_frame(cell_mv,
                                              cell_count,
                                              frame))
        {
            all_ok = false;
            break;
        }
    }

    return all_ok;
}

bool board_can2_tx_balance_status(uint16_t active_mask,
                                  uint8_t  balance_state,
                                  uint8_t  clean_cycle,
                                  uint8_t  spread_mv,
                                  uint8_t  cell_count,
                                  uint8_t  flags)
{
    uint8_t addr = board_get_address();
    uint8_t tx_data[8];

    tx_data[0] = (uint8_t)(active_mask >> 8);
    tx_data[1] = (uint8_t)(active_mask & 0xFF);
    tx_data[2] = balance_state;
    tx_data[3] = clean_cycle;
    tx_data[4] = spread_mv;
    tx_data[5] = cell_count;
    tx_data[6] = flags;
    tx_data[7] = bal2_status_counter++;

    return board_can_tx_standard_frame(&hfdcan2,
                                       CAN2_ID_BAL_STATUS_BASE
                                       + (uint32_t)addr,
                                       tx_data);
}

bool board_can2_tx_balance_command(uint8_t  board_id,
                                   uint16_t balance_mask,
                                   uint8_t  clean_cycle)
{
    uint8_t tx_data[8];

    tx_data[0] = (uint8_t)(balance_mask >> 8);
    tx_data[1] = (uint8_t)(balance_mask & 0xFF);
    tx_data[2] = clean_cycle;
    tx_data[3] = board_id;
    tx_data[4] = 0x00U;
    tx_data[5] = 0x00U;
    tx_data[6] = 0x00U;
    tx_data[7] = bal2_cmd_counter++;

    return board_can_tx_standard_frame(&hfdcan2,
                                       CAN2_ID_BAL_CMD_BASE
                                       + (uint32_t)(board_id & 0x0FU),
                                       tx_data);
}

#if 0

    /* ---- Build the TX header ----
     *
     * Identifier: 0x1B0 + board address
     * Standard 11-bit ID, classic CAN, 8 data bytes.
     * No error status indicator, no bit rate switching. */
    tx_header.Identifier          = CAN_ID_HEARTBEAT_BASE
                                    + (uint32_t)addr;
    tx_header.IdType              = FDCAN_STANDARD_ID;
    tx_header.TxFrameType         = FDCAN_DATA_FRAME;
    tx_header.DataLength          = FDCAN_DLC_BYTES_8;
    tx_header.ErrorStateIndicator = FDCAN_ESI_ACTIVE;
    tx_header.BitRateSwitch       = FDCAN_BRS_OFF;
    tx_header.FDFormat            = FDCAN_CLASSIC_CAN;
    tx_header.TxEventFifoControl  = FDCAN_NO_TX_EVENTS;
    tx_header.MessageMarker       = 0;

    /* ---- Build the 8-byte payload ---- */

    /* Byte 0: Board ID */
    tx_data[0] = addr;

    /* Byte 1: Board state (0=OK for now) */
    tx_data[1] = state;

    /* Byte 2: Active cell count */
    tx_data[2] = cell_count;

    /* Bytes 3-4: Min cell voltage, big-endian uint16.
     * Clamp negative values to 0 (shouldn't happen, but safe). */
    {
        uint16_t min_mv = (min_cell_mv > 0)
                          ? (uint16_t)min_cell_mv : 0U;
        tx_data[3] = (uint8_t)(min_mv >> 8);   /* High byte */
        tx_data[4] = (uint8_t)(min_mv & 0xFF);  /* Low byte  */
    }

    /* Bytes 5-6: Max cell voltage, big-endian uint16 */
    {
        uint16_t max_mv = (max_cell_mv > 0)
                          ? (uint16_t)max_cell_mv : 0U;
        tx_data[5] = (uint8_t)(max_mv >> 8);   /* High byte */
        tx_data[6] = (uint8_t)(max_mv & 0xFF);  /* Low byte  */
    }

    /* Byte 7: Rolling counter (wraps 0–255) */
    tx_data[7] = hb_rolling_counter;
    hb_rolling_counter++;  /* Wraps naturally at 255→0 */

    /* ---- Queue the frame for transmission ----
     *
     * HAL_FDCAN_AddMessageToTxFifoQ() copies the header and
     * data into the FDCAN message RAM TX FIFO.  The hardware
     * handles arbitration and transmission automatically.
     *
     * Returns HAL_ERROR if the TX FIFO is full — this happens
     * when no other node is ACKing (common with one board on
     * the bus and no termination).  Not a code bug. */
    if (HAL_FDCAN_AddMessageToTxFifoQ(&hfdcan1,
                                       &tx_header,
                                       tx_data) != HAL_OK)
    {
        /* TX FIFO full — likely no ACK from another node.
         * Don't spam debug output, just return false. */
        return false;
    }

    return true;
}
#endif


/* ================================================================
 * board_can_rx_heartbeat()
 *
 * Poll FDCAN1 RX FIFO 0 for a received heartbeat frame.
 * Non-blocking — returns instantly if the FIFO is empty.
 *
 * If a frame is available:
 *   - Copies the 8-byte payload into rx_data[]
 *   - Returns the board ID from byte 0 (0–7)
 *
 * If the FIFO is empty:
 *   - Returns -1
 *
 * The caller (application_loop on the master) can check the
 * return value and print the sender's address.
 * ================================================================ */
int8_t board_can_rx_heartbeat(uint8_t rx_data[8])
{
    return board_can_rx_heartbeat_bus(&hfdcan1, rx_data);
}

int8_t board_can2_rx_heartbeat(uint8_t rx_data[8])
{
    return board_can_rx_heartbeat_bus(&hfdcan2, rx_data);
}

bool board_can2_rx_message(uint32_t *std_id,
                           uint8_t   rx_data[8])
{
    return board_can_rx_message_bus(&hfdcan2, std_id, rx_data);
}

#if 0
    /* Check if any messages are waiting in RX FIFO 0.
     * GetRxFifoFillLevel returns the number of frames
     * stored in the FIFO — 0 means empty. */
    if (HAL_FDCAN_GetRxFifoFillLevel(&hfdcan1,
                                      FDCAN_RX_FIFO0) == 0)
    {
        return -1;  /* Nothing to read */
    }

    /* Read one frame from RX FIFO 0.
     * The HAL copies the header and data, then releases
     * the FIFO slot so the next frame can be stored. */
    if (HAL_FDCAN_GetRxMessage(&hfdcan1,
                                FDCAN_RX_FIFO0,
                                &rx_header,
                                rx_data) != HAL_OK)
    {
        return -1;  /* Read failed */
    }

    /* Use the CAN identifier as the source of truth for sender ID.
     * That makes the master robust even if a node's payload byte 0
     * is stale or misconfigured.  The filter already limits us to
     * 0x1B0..0x1B7, but we still sanity-check here. */
    if (rx_header.IdType != FDCAN_STANDARD_ID)
    {
        return -1;
    }

    if ((rx_header.Identifier < CAN_ID_HEARTBEAT_BASE) ||
        (rx_header.Identifier > (CAN_ID_HEARTBEAT_BASE + 7U)))
    {
        return -1;
    }

    sender_id = rx_header.Identifier - CAN_ID_HEARTBEAT_BASE;
    return (int8_t)sender_id;
}
#endif
